[package]
name = "rusvid_server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { version = "0.6.12", features = ["multipart"] }
fern = "0.6.2"
log = "0.4.17"
rusvid_lib = { path = "../rusvid_lib", version = "0.2.1" }
serde = "1.0.158"
serde_json = "1.0.95"
serde_yaml = "0.9.19"
tokio = { version = "1.27.0", features = ["full"] }
tokio-util = "0.7.7"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.0", features = ["full"] }
