version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=myAdmin
      - MINIO_ROOT_PASSWORD=myAdminPassword
    command: server /data --console-address ":9001"
    restart: unless-stopped

  minio_config:
    build:
      context: .
      dockerfile: Dockerfile.minio_conf
    environment:
      - STORAGE_URL=http://minio:9000
      - STORAGE_ROOT_USER=myAdmin
      - STORAGE_ROOT_PASSWORD=myAdminPassword
      - STORAGE_ACCESS_KEY=access_key_123
      - STORAGE_SECRET_KEY=access_secret_key_123
    depends_on:
      - minio
    links:
      - minio
