[workspace]
default-members = ["rusvid_cli"]
members = ["rusvid_lib", "rusvid_cli", "rusvid_server", "crates/*"]

[workspace.dependencies]
anyhow = "1.0.71"
thiserror = "1.0.40"

[workspace.package]
version = "0.2.1"
license = "Apache-2.0"
repository = "https://github.com/LetsMelon/rusvid"
