[package]
name = "rusvid_lib"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "SVG animator-library written in Rust"
repository = "https://github.com/LetsMelon/rusvid"
readme = "../README.md"
keywords = ["svg", "graphics", "animation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["hardware_transcoding"]
hardware_transcoding = ["dep:wgpu", "dep:futures-intrusive", "dep:bytemuck", "dep:pollster"]

[dependencies]
resvg = "0.23.0"
tiny-skia = "0.6.5"
usvg = "0.23.0"
debug-ignore = "1.0.2"
anyhow = "1.0.59"
image = "0.24.3"
bytemuck = { version = "1.12.1", optional = true }
pollster = { version = "0.2.5", optional = true }
wgpu = { version = "0.13", optional = true }
futures-intrusive = {version = "0.4", optional = true }

[dev-dependencies]
criterion = "0.3"
paste = "1.0"

[[bench]]
name = "image_render"
harness = false
