[package]
name = "rusvid_lib"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "SVG animator-library written in Rust"
repository = "https://github.com/LetsMelon/rusvid"
readme = "../README.md"
keywords = ["svg", "graphics", "animation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
easer = { git = "https://github.com/orhanbalci/rust-easing", rev = "872ea2c" }
glam = { version = "0.22.0", features = ["approx"] }
image = { version = "0.24", default-features = false, features = ["png", "bmp", "jpeg", "avif-encoder"] }
itertools = "0.10.5"
resvg = "0.23.0"
rusvid_core = { path = "../crates/core" }
tiny-skia = "0.6.5"
usvg = "0.23.0"
ravif = "0.9.0"
rgb = "0.8.34"

[dev-dependencies]
rayon = "*"
approx = "*"

[features]
parallel = ["image/jpeg_rayon"]
