[package]
name = "rusvid_lib"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "SVG animator-library written in Rust"
repository = "https://github.com/LetsMelon/rusvid"
readme = "../README.md"
keywords = ["svg", "graphics", "animation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[dependencies]
resvg = "0.23.0"
tiny-skia = "0.6.5"
usvg = "0.23.0"
debug-ignore = "1.0.3"
anyhow = "1.0.63"
image = "0.24.3"
rayon = "1.5.3"

[[bench]]
name = "image_render"
harness = false
