[package]
name = "rusvid_lib"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "SVG animator-library written in Rust"
repository = "https://github.com/LetsMelon/rusvid"
readme = "../README.md"
keywords = ["svg", "graphics", "animation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
easer = { git = "https://github.com/orhanbalci/rust-easing", rev = "872ea2c" }
glam = { version = "0.22.0", features = ["approx"] }
image = { workspace = true, features = ["png", "bmp", "jpeg"] }
itertools = "0.10.5"
log = "0.4"
resvg = { workspace = true }
rusvid_core = { path = "../crates/core" }
rusvid_effect = { path = "../crates/effect" }

[dev-dependencies]
rayon = "*"
approx = "*"

[features]
parallel = ["image/jpeg_rayon"]
