[package]
name = "rusvid_lib"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "SVG animator-library written in Rust"
repository = "https://github.com/LetsMelon/rusvid"
readme = "../README.md"
keywords = ["svg", "graphics", "animation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.25.0"
tiny-skia = "0.6.5"
usvg = "0.23.0"
anyhow = "1.0.65"
image = { version = "0.24", default-features = false, features = ["png", "bmp", "jpeg"] }
easer = { git = "https://github.com/orhanbalci/rust-easing", rev = "872ea2c" }
glam = { version = "0.21.3", features = ["approx"] }
rusvid_plane = { path = "../crates/plane" }
itertools = "0.10.5"

[dev-dependencies]
rayon = "*"
approx = "*"

[features]
parallel = ["image/jpeg_rayon"]
