[package]
name = "rusvid_lib"
edition = "2021"
description = "SVG animator-library written in Rust"
readme = "../README.md"
keywords = ["svg", "graphics", "animation"]
documentation = "https://docs.rs/rusvid_lib/"

version.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true, optional = true }
easer = { workspace = true }
glam = { workspace = true, features = ["approx"] }
itertools = { workspace = true }
log = { workspace = true }
mime = { workspace = true, optional = true }
miniz_oxide = { workspace = true, features = ["std"], optional = true }
multipart = { workspace = true, features = ["client"], optional = true }
paste = { workspace = true }
rayon = { workspace = true }
rusvid_core = { path = "../crates/core", version = "0.2.0" }
rusvid_effect = { path = "../crates/effect", version = "0.2.0" }
rusvid_video_encoder = { path = "../crates/video_encoder", version = "0.2.0" }
serde = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
static_assertions = { workspace = true }
ureq = { workspace = true, features = ["json"], optional = true }
url = { workspace = true, optional = true }

[dev-dependencies]
approx = { workspace = true }

[features]
default = []

serde = ["serialize", "deserialize"]
serialize = ["dep:serde", "rusvid_core/serialize"]
deserialize = ["dep:serde", "rusvid_core/deserialize"]

remote_renderer = [
    "dep:mime",
    "dep:multipart",
    "dep:serde_yaml",
    "dep:ureq",
    "dep:url",
    "rusvid_core/server",
    "serialize",
]

save_load = ["dep:bincode", "dep:miniz_oxide", "serde"]
