[package]
name = "rusvid_cli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.22"
fern = "0.6.1"
log = "0.4"
rusvid_lib = { path = "../rusvid_lib"}
