[package]
name = "rusvid_video_encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
ffmpeg-sys-next = { version = "5.1.1", default-features = false, features = [ "avformat", "swscale" ] }
rusvid_core = { path = "../core" }
thiserror = "1.0"
