[package]
name = "rusvid_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
image = { version = "0.24", default-features = false }
tiny-skia = { version = "0.6.5", default-features = false, features = ["std"] }

[features]
