[package]
name = "rusvid_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
image = { version = "0.24.4", default-features = false, optional = true }

[features]
default = ["plane"]
plane = ["dep:image"]
unsafe = []
