[package]
name = "rusvid_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
approx = "0.5.1"
concat-idents = "1.1.4"
glam = { version = "0.22.0", features = ["approx"] }
image = { workspace = true }
resvg = { workspace = true }
