[package]
name = "rusvid_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
concat-idents = "1.1.4"
flo_curves = "0.6.1"
glam = { version = "0.22.0", features = ["approx"] }
image = { workspace = true, features = ["png", "bmp", "jpeg"] }
resvg = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1.2.2", default-features = false, features = [ "v4", "fast-rng" ] }
geo = "0.23.1"

[dev-dependencies]
anyhow = { workspace = true }
image-compare = "0.2.3"
