[package]
name = "rusvid_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
concat-idents = "1.1.4"
flo_curves = "0.6.1"
geo = "0.23.1"
glam = { version = "0.22.0", features = ["approx"] }
image = { workspace = true, features = ["png", "bmp", "jpeg"] }
png = "0.17.7"
resvg = { workspace = true }
rhai = { version = "1.12.0", optional = true }
thiserror = { workspace = true }
uuid = { version = "1.2.2", default-features = false, features = [ "v4", "fast-rng", "js" ] }

[dev-dependencies]
anyhow = { workspace = true }
image-compare = "0.2.3"
itertools = "0.10.5"

[features]
scripting = ["dep:rhai"]
