[package]
name = "rusvid_core"
edition = "2021"
description = "Core library for rusvid"
readme = "./README.md"
keywords = ["svg", "graphics", "animation"]
documentation = "https://docs.rs/rusvid_core/"

version.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = { workspace = true }
cairo-rs = { workspace = true, optional = true }
concat-idents = { workspace = true }
flo_curves = { workspace = true } # TODO Maybe replace flo_curve with 'kurbo'
geo = { workspace = true }
glam = { workspace = true, features = ["approx"] }
image = { workspace = true, features = ["bmp", "jpeg"] }
itertools = { workspace = true }
paste = { workspace = true }
png = { workspace = true }
rand = { workspace = true }
redis = { workspace = true, optional = true }
resvg = { workspace = true, optional = true }
rhai = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = [
    "v4",
    "fast-rng",
    "js",
] } # TODO remove this features for default

[dev-dependencies]
anyhow = { workspace = true }
image-compare = { workspace = true }
itertools = { workspace = true }
strum = { workspace = true, features = ["derive"] }

[features]
default = ["resvg"]

serde = ["serialize", "deserialize"]
serialize = ["dep:serde", "glam/serde"]
deserialize = ["dep:serde", "glam/serde"]

scripting = ["dep:rhai"]

server = ["serde"]
redis = ["dep:redis"]

cairo = ["dep:cairo-rs"]
resvg = ["dep:resvg"]
