[package]
name = "rusvid_wasm"
edition = "2021"

version.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
console_error_panic_hook = { workspace = true }
js-sys = { workspace = true }
lazy_static = { workspace = true }
rusvid_core = { path = "../core", version = "0.2.0" }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = ["console"] }
