name: CI

on:
  push:
    paths:
      - '**.rs'
      - '**Cargo.**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.rs'
      - '**Cargo.**'
      - '.github/workflows/ci.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose --all-targets

      - name: Test
        run: cargo test

#      - name: Bench
#        run: cargo bench
