name: CI

on:
  push:
    paths:
      - '**.rs'
      - '**Cargo.**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.rs'
      - '**Cargo.**'
      - '.github/workflows/ci.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo

      - name: Cargo Target Cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-target

      - name: Build
        run: cargo build --verbose --all-targets

      - name: Test
        run: cargo test

#      - name: Bench
#        run: cargo bench
