name: CI - lib

on:
  push:
    paths:
      - "rusvid_lib/**.rs"
      - "**Cargo.**"
      - ".github/workflows/rusvid_lib_ci.yml"
  pull_request:
    paths:
      - "rusvid_lib/**.rs"
      - "**Cargo.**"
      - ".github/workflows/rusvid_lib_ci.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavutil-dev libavformat-dev libswscale-dev

      - name: Build
        run: cargo build --all-targets --all-features -p rusvid_lib
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"

      - name: Test
        run: cargo nextest run --all-features -p rusvid_lib
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
